export const WORD_LISTS = {
    en: {
        4: [
            "GAME", "PLAY", "WORD", "TIME", "LOVE", "HOPE", "BLUE", "CODE", "DATA", "FAST",
            "TREE", "BIRD", "ROAD", "PARK", "CITY", "BOOK", "FOOD", "MILK", "CAKE", "FISH",
            "BABY", "DOOR", "SONG", "NOTE", "RAIN", "SNOW", "WIND", "FIRE", "STAR", "MOON",
            "WALK", "TALK", "READ", "SWIM", "JUMP", "SING", "COOK", "BAKE", "GROW", "KNOW",
            "GIVE", "TAKE", "MAKE", "FIND", "LOOK", "WORK", "CALL", "HELP", "NEED", "FEEL",
            "GOOD", "KIND", "NICE", "WARM", "COLD", "COOL", "SOFT", "HARD", "LOUD", "QUIET",
            "HIGH", "DEEP", "LONG", "WIDE", "FULL", "FREE", "SAFE", "TRUE", "REAL", "SURE",
            "EASY", "BUSY", "RICH", "POOR", "FINE", "FAIR", "DARK", "PALE", "WEAK", "TALL",
            "LION", "BEAR", "WOLF", "DUCK", "FROG", "GOAT", "LAMB", "MULE", "PONY", "SEAL",
            "SWAN", "WASP", "WORM", "CRAB", "DEER", "HARE", "HAWK", "LARK", "MOTH", "TOAD",
            "BOAT", "SHIP", "CARS", "BIKE", "TAXI", "BUSES", "JETS", "VANS", "CART", "SLED",
            "RAFT", "TRAM", "RAIL", "MAST", "SAIL", "HELM", "DECK", "HULL", "KEEL", "OARS",
            "GOLD", "IRON", "LEAD", "ZINC", "COAL", "SAND", "CLAY", "DIRT", "DUST", "MUD",
            "ROCK", "SALT", "LIME", "SODA", "ACID", "BASE", "ATOM", "ION", "UNIT", "PART",
            "HEAD", "FACE", "EYES", "NOSE", "EARS", "HAIR", "SKIN", "HAND", "FOOT", "ARMS",
            "LEGS", "KNEE", "CHIN", "NECK", "BACK", "BONE", "NAIL", "TEETH", "LIPS", "TONG",
            "MIND", "SOUL", "LIFE", "SELF", "NAME", "DATE", "YEAR", "WEEK", "HOUR", "PAST",
            "ZERO", "FOUR", "FIVE", "NINE", "PLUS", "LESS", "HALF", "MANY", "MUCH", "SOME"
        ],
        5: [
            "APPLE", "BEACH", "CHAIR", "DANCE", "EAGLE", "FLAME", "GRAPE", "HOUSE", "IMAGE", "JOKER",
            "LEMON", "MANGO", "NIGHT", "OCEAN", "PIANO", "QUEEN", "RIVER", "SNAKE", "TIGER", "UMBRA",
            "VOICE", "WATER", "XENON", "YACHT", "ZEBRA", "BREAD", "CLOUD", "DREAM", "EARTH", "FRUIT",
            "GHOST", "HEART", "ISLAND", "JUICE", "KNIFE", "LIGHT", "MONEY", "NOISE", "ONION", "PAPER",
            "QUIET", "RADIO", "SUGAR", "TABLE", "UNCLE", "VIDEO", "WATCH", "YOUTH", "ALIVE", "BRAVE",
            "CLEAN", "DIRTY", "EARLY", "FRESH", "GREEN", "HAPPY", "HEAVY", "LARGE", "LUCKY", "MAGIC",
            "NOBLE", "PROUD", "QUICK", "READY", "SHARP", "SMART", "SWEET", "THICK", "TOUGH", "YOUNG",
            "BUILD", "CARRY", "DRINK", "ENTER", "FIGHT", "GUESS", "HURRY", "JUDGE", "LAUGH", "MARRY",
            "ORDER", "PAINT", "REACH", "SHARE", "SLEEP", "SMILE", "SPEAK", "STAND", "TEACH", "TOUCH",
            "VISIT", "WASTE", "WRITE", "ADULT", "AGENT", "ANGEL", "ANGER", "AWARD", "BASIS", "BIRTH",
            "BLOCK", "BLOOD", "BOARD", "BRAIN", "BREAK", "BROWN", "BUYER", "CAUSE", "CHAIN", "CHEST",
            "CHIEF", "CHILD", "CHINA", "CLAIM", "CLASS", "CLOCK", "COACH", "COAST", "COURT", "COVER",
            "CREAM", "CRIME", "CROWD", "CROWN", "CYCLE", "DEPTH", "DOUBT", "DRAFT", "DRAMA", "DRESS",
            "DRIVE", "ENEMY", "ENTRY", "ERROR", "EVENT", "FAITH", "FAULT", "FIELD", "FLOOR", "FOCUS",
            "FORCE", "FRAME", "FRONT", "GLASS", "GRANT", "GRASS", "GROUP", "GUIDE", "HORSE", "HOTEL",
            "INPUT", "ISSUE", "JAPAN", "JONES", "LAYER", "LEVEL", "LIMIT", "LUNCH", "MAJOR", "MARCH",
            "MATCH", "METAL", "MODEL", "MONTH", "MOTOR", "MOUTH", "MUSIC", "NORTH", "NOVEL", "NURSE",
            "OFFER", "OWNER", "PANEL", "PARTY", "PEACE", "PHASE", "PHONE", "PIECE", "PILOT", "PITCH",
            "PLACE", "PLANE", "PLANT", "PLATE", "POINT", "POUND", "POWER", "PRESS", "PRICE", "PRIDE"
        ],
        6: [
            "BANANA", "CASTLE", "DOCTOR", "FAMILY", "GARDEN", "JUNGLE", "MARKET", "ORANGE", "PLANET", "ROCKET",
            "ANIMAL", "BASKET", "CAMERA", "DINNER", "ENGINE", "FARMER", "GUITAR", "HAMMER", "INSECT", "JACKET",
            "KITTEN", "LADDER", "MIRROR", "NAPKIN", "OFFICE", "PENCIL", "RABBIT", "SCHOOL", "TOMATO", "VIOLIN",
            "WINDOW", "YELLOW", "ZOMBIE", "ACTION", "BOTTLE", "CANDLE", "DESERT", "ENERGY", "FOREST", "GALAXY",
            "HARBOR", "ISLAND", "JUNGLE", "KNIGHT", "LAWYER", "MUSEUM", "NATURE", "OBJECT", "PALACE", "QUARTZ",
            "RADISH", "SIGNAL", "TARGET", "VALLEY", "WEAPON", "ACCEPT", "BELONG", "CANCEL", "DECIDE", "EFFECT",
            "FINISH", "GATHER", "HANDLE", "IGNORE", "LISTEN", "MANAGE", "NOTICE", "OBTAIN", "PREFER", "REDUCE",
            "SEARCH", "TRAVEL", "UPDATE", "WONDER", "ABSENT", "ACTIVE", "ACTUAL", "ANNUAL", "BETTER", "BRIGHT",
            "COMMON", "DECENT", "DIRECT", "ENTIRE", "FAMOUS", "GENTLE", "GOLDEN", "HONEST", "HUMBLE", "LITTLE",
            "MENTAL", "MODERN", "NATIVE", "NORMAL", "PUBLIC", "RECENT", "SILENT", "SIMPLE", "SINGLE", "SMOOTH",
            "SOCIAL", "SUDDEN", "USEFUL", "VACANT", "VISUAL", "WEEKLY", "WINTER", "ADVICE", "AGENCY", "ANSWER",
            "APPEAL", "ASPECT", "ATTACK", "BATTLE", "BEAUTY", "BRANCH", "BREATH", "BRIDGE", "BUDGET", "BUTTON",
            "CAREER", "CHANCE", "CHANGE", "CHARGE", "CHOICE", "CHURCH", "CIRCLE", "CLIENT", "COFFEE", "COLUMN",
            "CORNER", "COUNTY", "COUPLE", "COURSE", "CREDIT", "DAMAGE", "DANGER", "DEBATE", "DEGREE", "DEMAND",
            "DESIGN", "DESIRE", "DETAIL", "DEVICE", "DOLLAR", "DOMAIN", "DRIVER", "EFFORT", "EXPERT", "EXPORT",
            "FACTOR", "FATHER", "FIGURE", "FINGER", "FLIGHT", "FRIEND", "FUTURE", "GROUND", "GROWTH", "HEALTH",
            "HEAVEN", "HEIGHT", "HORROR", "IMPACT", "INCOME", "INJURY", "ISLAND", "LEADER", "LENGTH", "LESSON",
            "LETTER", "LIQUID", "LIVING", "MANNER", "MASTER", "MEMBER", "MEMORY", "METHOD", "MIDDLE", "MINUTE",
            "MOMENT", "MOTHER", "MOTION", "NATION", "NUMBER", "OPTION", "OUTPUT", "PARENT", "PARISH", "PEOPLE"
        ]
    },
    he: {
        4: [
            "שלום", "תודה", "בוקר", "לילה", "חלון", "אביב", "סתיו", "חורף", "כוכב", "עולם",
            "אדמה", "אוהל", "אוכל", "אורח", "אותו", "אחרי", "אחת", "איזה", "איש", "איתו",
            "אלא", "אמא", "אמת", "אנחנו", "אני", "אף", "אצל", "ארץ", "אש", "אתה",
            "אתם", "אתן", "באה", "באו", "בגלל", "בדיוק", "בוא", "בחוץ", "בחור", "ביחד",
            "בין", "בית", "בכל", "בלי", "בן", "בסדר", "בעיה", "בעל", "בפנים", "בקשה",
            "בת", "גדול", "גוף", "גשם", "דבר", "דקה", "דרך", "הוא", "הולך", "הורים",
            "היום", "היא", "היה", "היו", "הייתי", "הכל", "הם", "הן", "הנה", "הרבה",
            "ויש", "זאת", "זה", "זוג", "זמן", "חדר", "חוף", "חוק", "חזק", "חיים",
            "חלק", "חשוב", "טוב", "טיול", "יד", "יהיה", "יודע", "יום", "יותר", "ילד",
            "ילדה", "ים", "יפה", "יצא", "יש", "ישן", "כאב", "כאן", "כבר", "כדור",
            "כובע", "כולם", "כוס", "כזה", "כחול", "כי", "כיסא", "ככה", "כל", "כלב",
            "כמה", "כסף", "כף", "כפר", "כתב", "לא", "לב", "לבן", "לבד", "לחם",
            "למה", "למעלה", "לפני", "לקח", "מאוד", "מבט", "מה", "מהר", "מוח", "מול",
            "מים", "מיטה", "מילה", "מישהו", "מלך", "ממש", "מצב", "מקום", "מרק", "משחק",
            "מתי", "מתנה", "נגד", "נהר", "נוף", "נחמד", "נמוך", "נפש", "נקי", "נשים",
            "נתן", "סבא", "סבתא", "סוף", "סוס", "סיפור", "סלט", "ספר", "סרט", "עבר",
            "עוד", "עוף", "עושה", "עיר", "על", "עם", "עץ", "עצם", "ערב", "פה",
            "פחד", "פעם", "פרי", "פתח", "צבע", "צד", "צחוק", "צריך", "קול", "קום"
        ],
        5: [
            "שולחן", "לימון", "אבטיח", "בקבוק", "מחברת", "מסעדה", "משפחה", "עבודה", "חברים", "תפילה",
            "אהבה", "אוויר", "אוטובוס", "אוכלוסיה", "אוניברסיטה", "אופניים", "אופי", "אוצר", "אור", "אז",
            "אח", "אחות", "אי", "אישה", "אמבטיה", "אמונה", "אמנות", "אנגלית", "אנשים", "אסור",
            "אף", "אפילו", "אפשר", "ארוחת", "אריה", "ארמון", "אשכולית", "אתמול", "בגדים", "בהצלחה",
            "בובה", "בחירה", "ביטחון", "בינוני", "ביצה", "ביקור", "בית", "בכבוד", "במקום", "בננה",
            "בנק", "בעלי", "בצל", "ברור", "ברזל", "בריאות", "בריכה", "בשר", "בתים", "גבינה",
            "גובה", "גזר", "גינה", "גלידה", "גמל", "גן", "גשר", "דבש", "דג", "דוד",
            "דודה", "דלת", "דמיון", "דף", "דקה", "דרום", "הבדל", "הודעה", "הזמנה", "החלטה",
            "היום", "הכי", "הלוואי", "הליכה", "המונים", "הנאה", "הפסקה", "הצגה", "הצלחה", "הר",
            "הרגשה", "התחלה", "זאב", "זהב", "זית", "זכר", "זמן", "זמר", "זקן", "זר",
            "חבר", "חברה", "חדשות", "חוט", "חום", "חופש", "חוץ", "חוקר", "חור", "חושך",
            "חזיר", "חי", "חידה", "חיה", "חינוך", "חיפוש", "חלום", "חלק", "חלב", "חלל",
            "חמאה", "חמור", "חנות", "חסר", "חצי", "חקלאות", "חרב", "חשבון", "חשמל", "חתול",
            "טבע", "טבעת", "טיסה", "טלפון", "טעם", "טעות", "יד", "יהודי", "ירח", "ירק",
            "ישראל", "כבוד", "כבש", "כדורגל", "כוהל", "כוח", "כוכב", "כוס", "כלום", "כלל",
            "כמות", "כנסת", "כנף", "כעס", "כף", "כפית", "כפר", "כתובת", "כתום", "לאן",
            "לב", "לבוש", "להתראות", "לוח", "לחם", "לילה", "למה", "למטה", "למוד", "לשון",
            "מאוחר", "מאמר", "מבנה", "מגדל", "מגבת", "מדינה", "מדע", "מדף", "מהר", "מזג"
        ],
        6: [
            "עגבניה", "מלפפון", "נעליים", "גרביים", "מחשבון", "מכונית", "חצוצרה", "דרבוקה", "קלרינט", "תרנגול",
            "כדורגל", "כדורסל", "אמבטיה", "משטרתי", "ממשלתי", "מטבחון", "מדרגות", "תמונות", "שעונים", "מנורות",
            "ארונות", "שמיכות", "סדינים", "חולצות", "חצאיות", "מעילים", "צעיפים", "כובעים", "מגפיים", "סנדלים",
            "מחשבים", "כיסאות", "מחברות", "ספרייה", "מסעדות", "חנויות", "רחובות", "מטבחים", "סלונים", "מרפסות",
            "חתולים", "עכברים", "ארנבים", "שועלים", "לוויתן", "דולפין", "כוכבים", "טורקיז", "מספרים", "שלושים",
            "ארבעים", "חמישים", "שמונים", "מיליון", "צהריים", "בלונים", "מחשבות", "זיכרון", "חלומות", "מציאות",
            "כישלון", "ניצחון", "פיקניק", "משקאות", "לקוחות", "מלצרית", "כספומט", "הלוואה", "משכורת", "עיפרון",
            "תלמידה", "ממתקים", "חטיפים", "משחקים", "קוביות", "פאזלים", "דומינו", "קלמרים", "יומנים", "מדבקות",
            "קולנוע", "מופעים", "שחקנית", "רקדנית", "אומנית", "משוררת", "מלחינה", "שדרנית", "תרופות", "בדיקות",
            "תורנות", "גימלים", "אזרחות", "בחירות", "מפלגות", "עירייה", "תושבים", "שכונות", "ספסלים", "כרטיסן",
            "נוסעים", "מזוודה", "תיירים", "קבוצות", "משפחות", "אותיות", "גרשיים", "ביקורת", "תשובות", "בריאות",
            "חיסרון", "אוהלים", "מזלגות", "סכינים", "מציתים", "חמוצים", "שקשוקה", "רביולי", "קוסקוס", "חריימה",
            "מלוואח", "גפילטע", "קרפיון", "וויסקי", "קוניאק", "שמפניה", "ספרייט", "תפוזים", "תנינים", "ציפורן",
            "דבורים", "זבובים", "יתושים", "עקרבים", "פרפרים", "עורבים", "דרורים", "טווסים", "קנגורו", "גורילה",
            "למורים", "חמורים", "מסננת", "מחבתות", "תבניות", "קומקום", "מגירות", "ראש עיר", "בית ספר", "יום הולדת"
        ]
    }
};

export const ALPHABETS = {
    en: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
    he: ['א', 'ב', 'ג', 'ד', 'ה', 'ו', 'ז', 'ח', 'ט', 'י', 'כ', 'ל', 'מ', 'נ', 'ס', 'ע', 'פ', 'צ', 'ק', 'ר', 'ש', 'ת']
};
